os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
jobs:
  fast_finish: true
  include:
    - python: "3.8"
      env: TOXENV=static
env:
  - TOXENV=unit
before_install:
  - python -m pip install --upgrade virtualenv
install:
  - pip install -U tox
  - pip install --force-reinstall setuptools==59.5.0
script: tox
notifications:
  email: false
deploy:
  # Allow travis-ci to deploy new tags to PyPI
  provider: pypi
  edge:
    branch: v1.8.45
  username: simple-salesforce
  password:
    secure: "RdkngWbRCGN5qSOk4babeda3w0jhsxB+zbuPjnFIOCHYz3OOQkIccXsoFPJso/E4k35mRNTU1J6PEBeL9W3KEtSgsl6k3lX8jamgJzkZU/HPoV8OH5tvybd3uiSikKA6EoxS5yfGjgTuSdOo07AzS69X4+FxNkRnTnug37tLjds="
  distributions: "sdist bdist_wheel"
  skip_existing: true
  cleanup: true
  on:
    tags: false
    all_branches: true
    repo: simple-salesforce/simple-salesforce
